name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: REACT_APP_BASE_URL=${{ vars.APP_BASE_URL }}
  deploy:
    name: Deploy
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Rerun server
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOMAIN: ${{ secrets.HOST }}
          FRONT_TAG: ${{ github.ref_name }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: DOMAIN,FRONT_TAG
          script: |
            echo "FRONT:${FRONT_TAG} BACK:${BACK_TAG}"
            docker compose --file deploy/docker-compose.yml up --pull always -d --remove-orphans frontend
