name: CD

on:
  push:
    branches: [ "deploy", "develop", "main" ]
  workflow_run:
    workflows: [Publish Docker]
    branches: [ "deploy", "develop", "main" ]
    types:
      - completed

jobs:
  build:
    name: Redeploy
    runs-on: ubuntu-latest
    steps:
    - name: Rerun server
      uses: appleboy/ssh-action@v1.0.0
      env:
        DOMAIN: ${{ secrets.HOST }}
        SENDER_API_KEY: ${{ secrets.SENDER_API_KEY }}
        FRONT_TAG: ${{ github.ref_name }}
        BACK_TAG: ${{ vars.BACK_TAG }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: DOMAIN,SENDER_API_KEY,FRONT_TAG,BACK_TAG
        script: |
          echo "FRONT:${FRONT_TAG} BACK:${BACK_TAG}"
          docker compose --file docker-compose/deploy/docker-compose.yml up --pull always -d --remove-orphans
